apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: dotnet-secret
  namespace: mediapipeline
data:
  DbSettings__ConnectionString: "SG9zdD1wc3FsLXN0YXRlZnVsc2V0LTAucHNxbC1zZXJ2aWNlLm1lZGlhcGlwZWxpbmUuc3ZjLmNsdXN0ZXIubG9jYWw7UG9ydD01NDMyO0RhdGFiYXNlPWRvdG5ldHNlcnZpY2VkYjtVc2VybmFtZT1wb3N0Z3JlcztQYXNzd29yZD1zZWNyZXRwYXNzd29yZA=="