apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-deployment
  namespace: mediapipeline
spec:
  minReadySeconds: 10
  replicas: 2
  selector:
    matchLabels:
      app: dotnet-service
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 50%
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: dotnet-service
    spec:
      containers:
        - command: ["/app/dotnetsevice"]
          envFrom:
            - configMapRef:
                name: dotnet-configmap
                optional: false
            - secretRef:
                name: dotnet-secret
                optional: false
          image: mediapipeline_dotnetservice:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 5
            httpGet:
              httpHeaders:
                - name: Content-Type
                  value: application/json
              path: /api/v1/infra/livez
              port: 5144
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 15 
          name: dotnetservice
          ports:
            - containerPort: 5144
              protocol: TCP
            - containerPort: 5145
              protocol: TCP
          readinessProbe:
            failureThreshold: 5
            httpGet:
              httpHeaders:
                - name: Content-Type
                  value: application/json
              path: /api/v1/infra/readyz
              port: 5144
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 3
            timeoutSeconds: 15
          resources:
            limits:
              memory: 500Mi
              cpu: 2
            requests:
              memory: 250Mi
              cpu: 1