apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: dotnet-secret
  namespace: mediapipeline
data:
  DbSettings__ConnectionString: "Host=psql-statefulset-0.psql-service.mediapipeline.svc.cluster.local;Port=5432;Database=dotnetservicedb;Username=postgres;Password=postgres"