apiVersion: v1
data:
  DATABASE_CONN_STRING: "aG9zdD1wc3FsLXN0YXRlZnVsc2V0LTAucHNxbC1zZXJ2aWNlLm1lZGlhcGlwZWxpbmUuc3ZjLmNsdXN0ZXIubG9jYWwgcG9ydD01NDMyIHVzZXI9cG9zdGdyZXMgcGFzc3dvcmQ9cG9zdGdyZXMgZGJuYW1lPWdvc2VydmljZWRiIHNzbG1vZGU9ZGlzYWJsZQ=="
immutable: true
kind: Secret
metadata:
  name: go-secret
  namespace: mediapipeline
type: Opaque