apiVersion: v1
data:
  DATABASE_CONN_STRING: "host=psql-statefulset-0.psql-service.mediapipeline.svc.cluster.local port=5432 user=postgres password=postgres dbname=goservicedb sslmode=disable"
immutable: true
kind: Secret
metadata:
  name: go-secret
  namespace: mediapipeline
type: Opaque