// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: file_counter_service.proto

package file_counter_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpsertFileCounterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertFileCounterRequest) Reset() {
	*x = UpsertFileCounterRequest{}
	mi := &file_file_counter_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertFileCounterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertFileCounterRequest) ProtoMessage() {}

func (x *UpsertFileCounterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_counter_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertFileCounterRequest.ProtoReflect.Descriptor instead.
func (*UpsertFileCounterRequest) Descriptor() ([]byte, []int) {
	return file_file_counter_service_proto_rawDescGZIP(), []int{0}
}

func (x *UpsertFileCounterRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpsertFileCounterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	LimitReached  *bool                  `protobuf:"varint,2,opt,name=limitReached,proto3,oneof" json:"limitReached,omitempty"`
	Error         *string                `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertFileCounterResponse) Reset() {
	*x = UpsertFileCounterResponse{}
	mi := &file_file_counter_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertFileCounterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertFileCounterResponse) ProtoMessage() {}

func (x *UpsertFileCounterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_counter_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertFileCounterResponse.ProtoReflect.Descriptor instead.
func (*UpsertFileCounterResponse) Descriptor() ([]byte, []int) {
	return file_file_counter_service_proto_rawDescGZIP(), []int{1}
}

func (x *UpsertFileCounterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpsertFileCounterResponse) GetLimitReached() bool {
	if x != nil && x.LimitReached != nil {
		return *x.LimitReached
	}
	return false
}

func (x *UpsertFileCounterResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

var File_file_counter_service_proto protoreflect.FileDescriptor

const file_file_counter_service_proto_rawDesc = "" +
	"\n" +
	"\x1afile_counter_service.proto\x12\x05proto\"2\n" +
	"\x18UpsertFileCounterRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"\x94\x01\n" +
	"\x19UpsertFileCounterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12'\n" +
	"\flimitReached\x18\x02 \x01(\bH\x00R\flimitReached\x88\x01\x01\x12\x19\n" +
	"\x05error\x18\x03 \x01(\tH\x01R\x05error\x88\x01\x01B\x0f\n" +
	"\r_limitReachedB\b\n" +
	"\x06_error2q\n" +
	"\x12FileCounterService\x12[\n" +
	"\x16UpsertFileCounterAsync\x12\x1f.proto.UpsertFileCounterRequest\x1a .proto.UpsertFileCounterResponseB\x1dZ\x1bpkg/pb/file_counter_serviceb\x06proto3"

var (
	file_file_counter_service_proto_rawDescOnce sync.Once
	file_file_counter_service_proto_rawDescData []byte
)

func file_file_counter_service_proto_rawDescGZIP() []byte {
	file_file_counter_service_proto_rawDescOnce.Do(func() {
		file_file_counter_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_file_counter_service_proto_rawDesc), len(file_file_counter_service_proto_rawDesc)))
	})
	return file_file_counter_service_proto_rawDescData
}

var file_file_counter_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_file_counter_service_proto_goTypes = []any{
	(*UpsertFileCounterRequest)(nil),  // 0: proto.UpsertFileCounterRequest
	(*UpsertFileCounterResponse)(nil), // 1: proto.UpsertFileCounterResponse
}
var file_file_counter_service_proto_depIdxs = []int32{
	0, // 0: proto.FileCounterService.UpsertFileCounterAsync:input_type -> proto.UpsertFileCounterRequest
	1, // 1: proto.FileCounterService.UpsertFileCounterAsync:output_type -> proto.UpsertFileCounterResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_file_counter_service_proto_init() }
func file_file_counter_service_proto_init() {
	if File_file_counter_service_proto != nil {
		return
	}
	file_file_counter_service_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_file_counter_service_proto_rawDesc), len(file_file_counter_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_file_counter_service_proto_goTypes,
		DependencyIndexes: file_file_counter_service_proto_depIdxs,
		MessageInfos:      file_file_counter_service_proto_msgTypes,
	}.Build()
	File_file_counter_service_proto = out.File
	file_file_counter_service_proto_goTypes = nil
	file_file_counter_service_proto_depIdxs = nil
}
