// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: file_counter_service.proto

package file_counter_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FileCounterService_UpsertFileCounterAsync_FullMethodName = "/proto.FileCounterService/UpsertFileCounterAsync"
)

// FileCounterServiceClient is the client API for FileCounterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileCounterServiceClient interface {
	UpsertFileCounterAsync(ctx context.Context, in *UpsertFileCounterRequest, opts ...grpc.CallOption) (*UpsertFileCounterResponse, error)
}

type fileCounterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFileCounterServiceClient(cc grpc.ClientConnInterface) FileCounterServiceClient {
	return &fileCounterServiceClient{cc}
}

func (c *fileCounterServiceClient) UpsertFileCounterAsync(ctx context.Context, in *UpsertFileCounterRequest, opts ...grpc.CallOption) (*UpsertFileCounterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertFileCounterResponse)
	err := c.cc.Invoke(ctx, FileCounterService_UpsertFileCounterAsync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileCounterServiceServer is the server API for FileCounterService service.
// All implementations must embed UnimplementedFileCounterServiceServer
// for forward compatibility.
type FileCounterServiceServer interface {
	UpsertFileCounterAsync(context.Context, *UpsertFileCounterRequest) (*UpsertFileCounterResponse, error)
	mustEmbedUnimplementedFileCounterServiceServer()
}

// UnimplementedFileCounterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileCounterServiceServer struct{}

func (UnimplementedFileCounterServiceServer) UpsertFileCounterAsync(context.Context, *UpsertFileCounterRequest) (*UpsertFileCounterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertFileCounterAsync not implemented")
}
func (UnimplementedFileCounterServiceServer) mustEmbedUnimplementedFileCounterServiceServer() {}
func (UnimplementedFileCounterServiceServer) testEmbeddedByValue()                            {}

// UnsafeFileCounterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileCounterServiceServer will
// result in compilation errors.
type UnsafeFileCounterServiceServer interface {
	mustEmbedUnimplementedFileCounterServiceServer()
}

func RegisterFileCounterServiceServer(s grpc.ServiceRegistrar, srv FileCounterServiceServer) {
	// If the following call panics, it indicates UnimplementedFileCounterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FileCounterService_ServiceDesc, srv)
}

func _FileCounterService_UpsertFileCounterAsync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertFileCounterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileCounterServiceServer).UpsertFileCounterAsync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileCounterService_UpsertFileCounterAsync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileCounterServiceServer).UpsertFileCounterAsync(ctx, req.(*UpsertFileCounterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FileCounterService_ServiceDesc is the grpc.ServiceDesc for FileCounterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileCounterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.FileCounterService",
	HandlerType: (*FileCounterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpsertFileCounterAsync",
			Handler:    _FileCounterService_UpsertFileCounterAsync_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "file_counter_service.proto",
}
